"use client";

import { useEffect, useState } from "react";
import { Bell, Building2, Check, CircleDollarSign, Loader2, Save, Settings2, ShieldCheck, Truck } from "lucide-react";

import { useAdminAccess } from "@/contexts/AdminContext";
import { saveStoreSettings, subscribeToStoreSettings } from "@/services/settings.service";
import { DEFAULT_STORE_SETTINGS, type StoreOperationsSettings } from "@/types/settings";

export default function AdminSettingsManager(){const {profile}=useAdminAccess();const [settings,setSettings]=useState<StoreOperationsSettings>(DEFAULT_STORE_SETTINGS);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
  useEffect(()=>subscribeToStoreSettings((next)=>{setSettings(next);setLoading(false);},(error)=>{setNotice(error.message);setLoading(false);}),[]);
  const set=<K extends keyof StoreOperationsSettings>(key:K,value:StoreOperationsSettings[K])=>setSettings((current)=>({...current,[key]:value}));
  async function save(){setBusy(true);setNotice("");try{await saveStoreSettings(settings,{uid:profile.uid,displayName:profile.displayName});setNotice("Operations settings securely saved and public-safe fields synchronized.");}catch(failure){setNotice(failure instanceof Error?failure.message:"Settings could not be saved.");}finally{setBusy(false);}}
  if(loading)return <div className="flex min-h-[70vh] items-center justify-center bg-[#F4EFE9]"><Loader2 className="animate-spin text-[#A8753C]"/></div>;
  return <div className="min-h-full bg-[#F4EFE9] px-4 py-6 text-[#191614] sm:px-7 lg:px-10 lg:py-9"><section className="rounded-[36px] bg-[linear-gradient(130deg,#171513,#2E2537)] p-7 text-white sm:p-10"><span className="inline-flex items-center gap-2 text-[8px] font-bold uppercase tracking-[.23em] text-[#DDB574]"><Settings2 size={14}/> Operations control</span><h1 className="mt-5 font-heading text-5xl sm:text-6xl">Set the house standard.</h1><p className="mt-4 max-w-2xl text-xs leading-6 text-white/55">Public-safe commerce configuration, audit history and future integration readiness—never client-bundled secrets.</p></section>{notice&&<p role="status" className="mt-4 rounded-2xl border border-[#E1D2BC] bg-[#FFF7EA] p-4 text-xs text-[#775936]">{notice}</p>}
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_320px]"><main className="space-y-5"><Group title="Store identity" icon={Building2}><Field label="Store name" value={settings.storeName} onChange={(v)=>set("storeName",v)}/><Field label="Legal name" value={settings.legalName} onChange={(v)=>set("legalName",v)}/><Field label="Support email" value={settings.supportEmail} onChange={(v)=>set("supportEmail",v)}/><Field label="Support phone" value={settings.supportPhone} onChange={(v)=>set("supportPhone",v)}/></Group>
      <Group title="Commerce rules" icon={CircleDollarSign}><Field label="Currency" value={settings.currency} onChange={(v)=>set("currency",v)}/><Field label="Locale" value={settings.locale} onChange={(v)=>set("locale",v)}/><NumberField label="Tax rate %" value={settings.taxRate} onChange={(v)=>set("taxRate",v)}/><NumberField label="Return window days" value={settings.returnWindowDays} onChange={(v)=>set("returnWindowDays",v)}/><Field label="Order prefix" value={settings.orderPrefix} onChange={(v)=>set("orderPrefix",v)}/><Field label="Invoice prefix" value={settings.invoicePrefix} onChange={(v)=>set("invoicePrefix",v)}/></Group>
      <Group title="Shipping" icon={Truck}><NumberField label="Complimentary threshold" value={settings.shippingThreshold} onChange={(v)=>set("shippingThreshold",v)}/><NumberField label="Standard shipping fee" value={settings.standardShippingFee} onChange={(v)=>set("standardShippingFee",v)}/><Toggle label="Tax-inclusive prices" checked={settings.taxInclusive} onChange={(v)=>set("taxInclusive",v)}/><Toggle label="Maintenance mode" checked={settings.maintenanceMode} onChange={(v)=>set("maintenanceMode",v)}/></Group>
      <Group title="Notifications" icon={Bell}><Toggle label="Email notifications" checked={settings.emailNotifications} onChange={(v)=>set("emailNotifications",v)}/><Toggle label="Push notifications" checked={settings.pushNotifications} onChange={(v)=>set("pushNotifications",v)}/><Toggle label="Low-stock alerts" checked={settings.lowStockNotifications} onChange={(v)=>set("lowStockNotifications",v)}/></Group></main>
      <aside className="h-fit rounded-[28px] bg-[#1D1A18] p-6 text-white xl:sticky xl:top-24"><ShieldCheck className="text-[#DDB574]"/><h2 className="mt-5 font-heading text-3xl">Commerce safety</h2><p className="mt-3 text-[10px] leading-5 text-white/50">Live mode remains locked until a verified gateway configuration exists.</p><label className="mt-6 grid gap-2 text-[7px] font-bold uppercase tracking-[.16em] text-white/45">Commerce mode<select value={settings.commerceMode} onChange={(e)=>set("commerceMode",e.target.value as StoreOperationsSettings["commerceMode"])} className="h-11 rounded-xl border border-white/10 bg-[#28231F] px-3 text-xs normal-case text-white"><option value="portfolio">Payment disabled</option><option value="live">Live (requires gateway)</option></select></label><div className="mt-5 space-y-2">{[["Gateway",settings.gatewayIntegration],["Carrier",settings.carrierIntegration]].map(([label,status])=><div key={label} className="flex items-center justify-between rounded-xl bg-white/5 p-3 text-[9px]"><span className="text-white/50">{label}</span><span className="flex items-center gap-1 text-[#DDB574]"><Check size={11}/>{status}</span></div>)}</div><button onClick={save} disabled={busy} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-[#DDB574] text-[8px] font-bold uppercase tracking-[.14em] text-[#1D1812] disabled:opacity-50">{busy?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>} Save settings</button><p className="mt-4 text-[8px] leading-4 text-white/35">{settings.updatedAt?`Last synchronized ${new Date(settings.updatedAt).toLocaleString("en-IN")}`:"Not synchronized yet"}</p></aside></div></div>}
function Group({title,icon:Icon,children}:{title:string;icon:typeof Building2;children:React.ReactNode}){return <section className="rounded-[28px] border border-[#E1D7CD] bg-white p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F4ECE2] text-[#A8753C]"><Icon size={17}/></span><h2 className="font-heading text-3xl">{title}</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{children}</div></section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#857A71]">{label}<input value={value} onChange={(e)=>onChange(e.target.value)} className="h-12 rounded-2xl border border-[#DED4CA] px-4 text-xs font-medium normal-case tracking-normal outline-none focus:border-[#A8753C]"/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className="grid gap-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#857A71]">{label}<input type="number" min={0} value={value} onChange={(e)=>onChange(Number(e.target.value))} className="h-12 rounded-2xl border border-[#DED4CA] px-4 text-xs font-medium normal-case tracking-normal outline-none focus:border-[#A8753C]"/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <button type="button" onClick={()=>onChange(!checked)} role="switch" aria-checked={checked} className="flex min-h-12 items-center justify-between rounded-2xl border border-[#DED4CA] px-4 text-left text-xs"><span>{label}</span><span className={`relative h-6 w-11 rounded-full transition ${checked?"bg-[#1D1A18]":"bg-[#D8CFC7]"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${checked?"left-6":"left-1"}`}/></span></button>}
