"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Download, Heart, PackageSearch, RotateCcw, ShoppingBag, Sparkles, Users } from "lucide-react";

import { subscribeToCommerceAnalytics } from "@/services/analytics.service";
import { EMPTY_COMMERCE_ANALYTICS, type CommerceAnalytics } from "@/types/analytics";

const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value);
function pct(value:number){return `${value.toFixed(1)}%`;}

export default function AdminAnalyticsDashboard(){
  const [data,setData]=useState<CommerceAnalytics>(EMPTY_COMMERCE_ANALYTICS);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>subscribeToCommerceAnalytics((next)=>{setData(next);setLoading(false);},(failure)=>{setError(failure.message);setLoading(false);}),[]);
  const maxTrend=useMemo(()=>Math.max(1,...data.trend.map((item)=>item.revenue)),[data.trend]);
  function exportCsv(){const rows=[["Metric","Value"],["Revenue",data.revenue],["Orders",data.orders],["Customers",data.customers],["AOV",data.averageOrderValue],["Return rate",data.returnRate],["Cancellation rate",data.cancellationRate]];const blob=new Blob([rows.map((row)=>row.join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`styloverse-analytics-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url);}
  const metrics=[{label:"Gross revenue",value:money(data.revenue),caption:`${data.orders} orders`,icon:BarChart3},{label:"Customers",value:String(data.customers),caption:`${pct(data.conversionRate)} conversion`,icon:Users},{label:"Average order",value:money(data.averageOrderValue),caption:`${money(data.paymentReceived)} received`,icon:ShoppingBag},{label:"Inventory alerts",value:String(data.lowStockProducts),caption:`${data.activeDiscounts} active campaigns`,icon:PackageSearch}];
  return <div className="min-h-full bg-[#F4EFE9] px-4 py-6 text-[#191614] sm:px-7 lg:px-10 lg:py-9">
    <section className="rounded-[36px] bg-[radial-gradient(circle_at_82%_10%,rgba(105,76,231,.32),transparent_34%),linear-gradient(130deg,#171513,#302438)] p-7 text-white sm:p-10"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/12 bg-white/7 px-4 py-2 text-[8px] font-bold uppercase tracking-[.22em] text-[#E2B979]"><Sparkles size={13}/> Real commerce intelligence</span><h1 className="mt-6 font-heading text-5xl leading-[.92] sm:text-6xl">Decisions, grounded in truth.</h1><p className="mt-4 max-w-2xl text-xs leading-6 text-white/55">Live Firebase orders, customers, inventory, discounts and aftercare—no generated metrics.</p></div><button onClick={exportCsv} className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-white px-6 text-[9px] font-bold uppercase tracking-[.13em] text-[#191614]"><Download size={14}/> Export report</button></div></section>
    {error&&<p className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-xs text-red-700">{error}</p>}
    <section aria-label="Commerce metrics" className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,caption,icon:Icon})=><article key={label} className="rounded-[26px] border border-[#E1D7CD] bg-white p-5"><Icon size={17} className="text-[#A8753C]"/><strong className="mt-5 block font-heading text-3xl">{loading?"—":value}</strong><p className="mt-1 text-[8px] font-bold uppercase tracking-[.16em] text-[#857B73]">{label}</p><p className="mt-3 text-[9px] text-[#9B9087]">{caption}</p></article>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><article className="rounded-[30px] border border-[#E1D7CD] bg-white p-6"><p className="text-[8px] font-bold uppercase tracking-[.2em] text-[#A8753C]">Revenue movement</p><h2 className="mt-2 font-heading text-3xl">Sales pulse</h2>{data.trend.length?<div className="mt-8 flex h-64 items-end gap-3 overflow-x-auto">{data.trend.map((point)=><div key={point.label} className="flex min-w-14 flex-1 flex-col items-center gap-2"><span className="text-[8px] text-[#81766E]">{money(point.revenue)}</span><div className="w-full rounded-t-2xl bg-gradient-to-t from-[#221D1A] to-[#DDB574]" style={{height:`${Math.max(8,(point.revenue/maxTrend)*180)}px`}}/><span className="text-[7px] font-bold uppercase tracking-[.1em] text-[#91867D]">{point.label}</span></div>)}</div>:<Empty label="No completed order trend yet."/>}</article>
      <article className="rounded-[30px] bg-[#1D1A18] p-6 text-white"><p className="text-[8px] font-bold uppercase tracking-[.2em] text-[#DDB574]">Journey health</p><div className="mt-5 space-y-3">{[["Cart abandonment",pct(data.cartAbandonmentRate),ShoppingBag],["Wishlist conversion",pct(data.wishlistConversionRate),Heart],["Return rate",pct(data.returnRate),RotateCcw],["Cancellation rate",pct(data.cancellationRate),RotateCcw]].map(([label,value,Icon])=>{const I=Icon as typeof Heart;return <div key={String(label)} className="flex items-center justify-between rounded-2xl border border-white/8 bg-white/5 p-4"><span className="flex items-center gap-3 text-[9px] text-white/55"><I size={14} className="text-[#DDB574]"/>{String(label)}</span><strong className="font-heading text-xl">{String(value)}</strong></div>})}</div></article></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><Ranking title="Best-selling products" items={data.bestProducts}/><Ranking title="Category performance" items={data.bestCategories}/></section>
  </div>;
}
function Empty({label}:{label:string}){return <div className="mt-8 flex min-h-52 items-center justify-center rounded-2xl border border-dashed border-[#D9CEC4] text-xs text-[#8B8077]">{label}</div>}
function Ranking({title,items}:{title:string;items:CommerceAnalytics["bestProducts"]}){return <article className="rounded-[28px] border border-[#E1D7CD] bg-white p-6"><h2 className="font-heading text-3xl">{title}</h2>{items.length?<div className="mt-5 divide-y divide-[#EEE6DF]">{items.map((item,index)=><div key={item.id} className="grid grid-cols-[28px_1fr_auto] items-center gap-3 py-4"><span className="text-[9px] font-bold text-[#B18049]">0{index+1}</span><div><strong className="text-xs">{item.label}</strong><p className="mt-1 text-[8px] text-[#948980]">{money(item.secondary)} value</p></div><span className="font-heading text-xl">{item.value}</span></div>)}</div>:<Empty label="Sales data will appear after real orders."/>}</article>}
