"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Gift, Loader2, PackageCheck, Ruler, Save, Shirt, Sparkles, WandSparkles } from "lucide-react";

import { useAuth } from "@/contexts/AuthContext";
import { useCatalogProducts } from "@/hooks/useCatalogProducts";
import { getRecentlyViewed } from "@/lib/recently-viewed";
import { subscribeToUserCart } from "@/services/cart.service";
import { subscribeToStoreCollections } from "@/services/content-admin.service";
import { subscribeToUserOrders } from "@/services/order.service";
import { buildOccasionEdit, buildPersonalRecommendations } from "@/services/recommendation.service";
import { saveStyleProfile, subscribeToStyleProfile } from "@/services/style-profile.service";
import { subscribeToUserWishlist } from "@/services/wishlist.service";
import { EMPTY_STYLE_PROFILE, type StyleProfile } from "@/types/personalization";
import type { StoreCollection } from "@/types/content-admin";

const categoryOptions=["MEN","WOMEN","STREETWEAR","FOOTWEAR","ACCESSORIES","WINTER"];
const colorOptions=["Black","Ivory","Beige","Blue","Green","Red","Gold","Grey"];
const occasionOptions=["wedding","work","weekend","gift"];
function toggle(values:string[],value:string){return values.includes(value)?values.filter((item)=>item!==value):[...values,value];}

export default function PersonalizationStudio(){const {user}=useAuth();const products=useCatalogProducts();const [profile,setProfile]=useState<StyleProfile>(EMPTY_STYLE_PROFILE);const [wishlist,setWishlist]=useState<string[]>([]);const [cart,setCart]=useState<string[]>([]);const [purchased,setPurchased]=useState<string[]>([]);const [drops,setDrops]=useState<StoreCollection[]>([]);const [occasion,setOccasion]=useState("wedding");const [giftBudget,setGiftBudget]=useState(8000);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
  useEffect(()=>{const collectionStop=subscribeToStoreCollections((items)=>setDrops(items.filter((item)=>item.status==="scheduled"&&new Date(item.publishAt).getTime()>Date.now())));if(!user)return collectionStop;const stops=[collectionStop,subscribeToStyleProfile(user.uid,setProfile,(e)=>setNotice(e.message)),subscribeToUserWishlist(user.uid,setWishlist),subscribeToUserCart(user.uid,(items)=>setCart(items.map((item)=>String(item.productId??item.id??item.slug??"")))),subscribeToUserOrders(user.uid,(orders)=>setPurchased([...new Set(orders.filter((order)=>String(order.status).toLowerCase()==="delivered").flatMap((order)=>(Array.isArray(order.items)?order.items:[]).map((raw)=>{const item=raw as Record<string,unknown>;return String(item.productDocumentId??item.productId??item.id??item.slug??"");}).filter(Boolean)))]))];return()=>stops.forEach((stop)=>stop());},[user]);
  const recent=useMemo(()=>typeof window==="undefined"?[]:getRecentlyViewed().map((item)=>String(item.id)),[]);
  const recommendations=useMemo(()=>buildPersonalRecommendations(products,profile,{wishlistIds:wishlist,cartIds:cart,recentIds:recent}),[products,profile,wishlist,cart,recent]);
  const occasionEdit=useMemo(()=>buildOccasionEdit(products,occasion,giftBudget),[products,occasion,giftBudget]);
  async function save(){if(!user)return;setBusy(true);setNotice("");try{await saveStyleProfile({...profile,userId:user.uid});setNotice("Your private style profile is synchronized.");}catch(failure){setNotice(failure instanceof Error?failure.message:"Profile could not be saved.");}finally{setBusy(false);}}
  return <div className="pb-10"><section className="relative overflow-hidden rounded-[34px] bg-[radial-gradient(circle_at_82%_10%,rgba(118,82,243,.34),transparent_34%),linear-gradient(130deg,#171513,#30243B)] p-6 text-white sm:p-9"><span className="inline-flex items-center gap-2 rounded-full border border-white/12 bg-white/7 px-4 py-2 text-[8px] font-bold uppercase tracking-[.22em] text-[#E0B576]"><WandSparkles size={13}/> Personal style intelligence</span><h1 className="mt-6 max-w-4xl font-heading text-5xl leading-[.9] sm:text-6xl">A wardrobe shaped around you.</h1><p className="mt-5 max-w-2xl text-xs leading-6 text-white/55">Recommendations use your real saved, bag, browsing and fit signals. Your profile remains scoped to your account.</p></section>{notice&&<p role="status" className="mt-4 rounded-2xl border border-[#E3D3BC] bg-[#FFF7EA] p-4 text-xs text-[#795A36]">{notice}</p>}
    <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_340px]"><div className="space-y-5"><Panel title="Style signature" icon={Sparkles}><Choice label="Preferred categories" options={categoryOptions} values={profile.preferredCategories} onChange={(v)=>setProfile({...profile,preferredCategories:toggle(profile.preferredCategories,v)})}/><Choice label="Colours" options={colorOptions} values={profile.preferredColors} onChange={(v)=>setProfile({...profile,preferredColors:toggle(profile.preferredColors,v)})}/><Choice label="Occasions" options={occasionOptions} values={profile.preferredOccasions} onChange={(v)=>setProfile({...profile,preferredOccasions:toggle(profile.preferredOccasions,v)})}/></Panel><Panel title="Fit passport" icon={Ruler}><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(["chest","waist","hips","height"] as const).map((key)=><Field key={key} label={`${key} (cm)`} value={profile.measurements[key]} onChange={(v)=>setProfile({...profile,measurements:{...profile.measurements,[key]:v}})}/>)}</div><div className="mt-4 grid grid-cols-3 gap-3">{(["top","bottom","footwear"] as const).map((key)=><Field key={key} label={`${key} size`} value={profile.sizes[key]} onChange={(v)=>setProfile({...profile,sizes:{...profile.sizes,[key]:v}})}/>)}</div></Panel><Panel title="Digital wardrobe" icon={Shirt}><p className="text-xs leading-5 text-[#81766E]">Purchased products can be retained here for outfit pairing and duplicate-aware recommendations.</p><p className="mt-4 font-heading text-3xl">{profile.wardrobeProductIds.length} <span className="text-base text-[#94887F]">saved pieces</span></p></Panel></div>
      <aside className="h-fit rounded-[28px] bg-[#1D1A18] p-6 text-white xl:sticky xl:top-24"><PackageCheck className="text-[#DDB574]"/><h2 className="mt-5 font-heading text-3xl">Private preferences</h2><div className="mt-5 grid gap-3"><Field label="Minimum budget" type="number" value={String(profile.budgetMin)} onChange={(v)=>setProfile({...profile,budgetMin:Number(v)})}/><Field label="Maximum budget" type="number" value={String(profile.budgetMax)} onChange={(v)=>setProfile({...profile,budgetMax:Number(v)})}/><label className="grid gap-2 text-[7px] font-bold uppercase tracking-[.15em] text-white/45">Packaging<select value={profile.packagingPreference} onChange={(e)=>setProfile({...profile,packagingPreference:e.target.value as StyleProfile["packagingPreference"]})} className="h-11 rounded-xl border border-white/10 bg-[#28231F] px-3 text-xs normal-case text-white"><option value="signature">Signature</option><option value="gift">Gift presentation</option><option value="minimal">Minimal</option></select></label></div><button onClick={save} disabled={busy} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-[#DDB574] text-[8px] font-bold uppercase tracking-[.14em] text-[#1D1812]">{busy?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>} Save profile</button></aside></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-[28px] border border-[#E1D7CD] bg-[#FCF8F3] p-6"><p className="text-[8px] font-bold uppercase tracking-[.2em] text-[#A8753C]">Digital wardrobe truth</p><p className="mt-3 font-heading text-4xl">{new Set([...profile.wardrobeProductIds,...purchased]).size} owned pieces</p><p className="mt-2 text-xs leading-5 text-[#81766E]">Delivered order pieces are synchronized automatically; private additions remain account-scoped.</p></div><div className="rounded-[28px] bg-[#211C1A] p-6 text-white"><p className="text-[8px] font-bold uppercase tracking-[.2em] text-[#DDB574]">Private collection access</p><p className="mt-3 font-heading text-3xl">{drops.length?`${drops.length} scheduled drop${drops.length===1?"":"s"}`:"No private drop scheduled"}</p><p className="mt-2 text-xs leading-5 text-white/50">Only real CMS-scheduled collections appear here. No invented countdowns or launch dates.</p></div></section>
    <ProductRail title="Selected for your signals" products={recommendations}/>
    <section className="mt-6 rounded-[30px] border border-[#E1D7CD] bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="flex items-center gap-2 text-[8px] font-bold uppercase tracking-[.2em] text-[#A8753C]"><Gift size={13}/> Gift & occasion finder</span><h2 className="mt-2 font-heading text-4xl">Build a considered edit.</h2></div><div className="flex gap-2"><select value={occasion} onChange={(e)=>setOccasion(e.target.value)} className="h-11 rounded-full border border-[#DDD3C9] px-4 text-xs">{occasionOptions.map((item)=><option key={item}>{item}</option>)}</select><input aria-label="Gift budget" type="number" value={giftBudget} onChange={(e)=>setGiftBudget(Number(e.target.value))} className="h-11 w-28 rounded-full border border-[#DDD3C9] px-4 text-xs"/></div></div><ProductGrid products={occasionEdit}/></section>
  </div>}
function Panel({title,icon:Icon,children}:{title:string;icon:typeof Sparkles;children:React.ReactNode}){return <section className="rounded-[28px] border border-[#E1D7CD] bg-white p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F3EBE1] text-[#A8753C]"><Icon size={17}/></span><h2 className="font-heading text-3xl">{title}</h2></div><div className="mt-6">{children}</div></section>}
function Choice({label,options,values,onChange}:{label:string;options:string[];values:string[];onChange:(value:string)=>void}){return <div className="mt-4 first:mt-0"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#857A71]">{label}</p><div className="mt-2 flex flex-wrap gap-2">{options.map((item)=><button type="button" key={item} onClick={()=>onChange(item)} aria-pressed={values.includes(item)} className={`min-h-10 rounded-full border px-4 text-[8px] font-bold uppercase tracking-[.1em] ${values.includes(item)?"border-[#1D1A18] bg-[#1D1A18] text-white":"border-[#DDD3C9]"}`}>{item}</button>)}</div></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="grid gap-2 text-[7px] font-bold uppercase tracking-[.15em] text-[#857A71]">{label}<input type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="h-11 rounded-xl border border-[#DDD3C9] bg-white px-3 text-xs font-medium normal-case tracking-normal text-[#191614] outline-none"/></label>}
function ProductRail({title,products}:{title:string;products:ReturnType<typeof buildPersonalRecommendations>}){return <section className="mt-6"><h2 className="font-heading text-4xl">{title}</h2><ProductGrid products={products}/></section>}
function ProductGrid({products}:{products:ReturnType<typeof buildPersonalRecommendations>}){return products.length?<div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{products.slice(0,4).map((product)=><Link key={product.slug} href={`/product/${product.slug}`} className="group overflow-hidden rounded-[22px] border border-[#E1D7CD] bg-[#F7F2ED]"><div className="relative aspect-[4/5] overflow-hidden"><Image src={product.image} alt={product.name} fill sizes="(max-width:768px) 50vw, 25vw" className="object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-4"><p className="text-[7px] font-bold uppercase tracking-[.14em] text-[#A8753C]">{product.category}</p><h3 className="mt-2 font-heading text-lg leading-tight">{product.name}</h3><p className="mt-2 text-xs font-bold">₹{product.price.toLocaleString("en-IN")}</p></div></Link>)}</div>:<p className="mt-5 rounded-2xl border border-dashed border-[#D8CEC5] p-8 text-center text-xs text-[#887D74]">No matching real products yet. Adjust the style signals.</p>}
