export const RETURN_STATUSES = ["requested", "approved", "rejected", "pickup_scheduled", "in_transit", "received", "inspected", "exchange_reserved", "refund_pending", "refund_processing", "completed", "closed"] as const;
export type ReturnStatus = (typeof RETURN_STATUSES)[number];
export type ReturnResolution = "return" | "exchange";
export type ReturnItem = { itemId: string; productId: string; variantId: string; name: string; image: string; quantity: number; size: string; color: string; requestedSize: string; requestedColor: string };
export type ReturnAuditEntry = { id: string; action: string; detail: string; actorUid: string; actorName: string; createdAt: string };
export type ReturnRequest = {
  id: string;
  orderId: string;
  userId: string;
  customerName: string;
  customerEmail: string;
  resolution: ReturnResolution;
  reason: string;
  details: string;
  evidenceUrls: string[];
  items: ReturnItem[];
  status: ReturnStatus;
  pickupCarrier: string;
  pickupTrackingId: string;
  pickupScheduledAt: string;
  inspectionOutcome: "pending" | "restock" | "damaged" | "rejected";
  inventoryAdjustmentStatus: "not_required" | "pending" | "processing" | "completed" | "failed";
  inventoryAdjustmentError: string;
  inventoryAdjustedAt: string;
  refundMethod: "original" | "bank" | "upi" | "store_credit" | "not_applicable";
  refundDestination: {
    accountHolder: string;
    bankName: string;
    accountLast4: string;
    upiId: string;
  };
  refundAmount: number;
  refundStatus: "not_applicable" | "pending" | "processing" | "completed" | "failed";
  refundReference: string;
  adminNote: string;
  createdAt: string;
  updatedAt: string;
  auditTrail: ReturnAuditEntry[];
};
