import { doc, onSnapshot, serverTimestamp, writeBatch, type DocumentData, type Unsubscribe } from "firebase/firestore";

import { db } from "@/lib/firebase";
import { DEFAULT_STORE_SETTINGS, type StoreOperationsSettings } from "@/types/settings";

function text(value:unknown,fallback=""){return typeof value==="string"?value.trim():fallback;}
function normalize(data:DocumentData):StoreOperationsSettings{return {...DEFAULT_STORE_SETTINGS,...data,id:"global",storeName:text(data.storeName,DEFAULT_STORE_SETTINGS.storeName),currency:text(data.currency,"INR"),locale:text(data.locale,"en-IN"),shippingThreshold:Math.max(0,Number(data.shippingThreshold)||0),standardShippingFee:Math.max(0,Number(data.standardShippingFee)||0),taxRate:Math.max(0,Number(data.taxRate)||0),returnWindowDays:Math.max(1,Number(data.returnWindowDays)||7),commerceMode:data.commerceMode==="live"?"live":"portfolio",gatewayIntegration:data.gatewayIntegration==="configured"?"configured":"disabled",carrierIntegration:data.carrierIntegration==="configured"?"configured":"disabled",auditTrail:Array.isArray(data.auditTrail)?data.auditTrail:[],updatedAt:data.updatedAt?.toDate?.().toISOString?.()??text(data.updatedAt)};}
export function subscribeToStoreSettings(onData:(settings:StoreOperationsSettings)=>void,onError?:(error:Error)=>void):Unsubscribe{return onSnapshot(doc(db,"storeSettings","global"),(snapshot)=>onData(snapshot.exists()?normalize(snapshot.data()):DEFAULT_STORE_SETTINGS),(error)=>onError?.(error));}
export function subscribeToPublicStoreSettings(onData:(settings:Pick<StoreOperationsSettings,"storeName"|"supportEmail"|"currency"|"locale"|"shippingThreshold"|"standardShippingFee"|"returnWindowDays"|"maintenanceMode"|"commerceMode">)=>void,onError?:(error:Error)=>void):Unsubscribe{return onSnapshot(doc(db,"publicStoreSettings","public"),(snapshot)=>{const data=snapshot.exists()?snapshot.data():{};onData({storeName:text(data.storeName,DEFAULT_STORE_SETTINGS.storeName),supportEmail:text(data.supportEmail,DEFAULT_STORE_SETTINGS.supportEmail),currency:text(data.currency,"INR"),locale:text(data.locale,"en-IN"),shippingThreshold:Math.max(0,Number(data.shippingThreshold)||DEFAULT_STORE_SETTINGS.shippingThreshold),standardShippingFee:Math.max(0,Number(data.standardShippingFee)||DEFAULT_STORE_SETTINGS.standardShippingFee),returnWindowDays:Math.max(1,Number(data.returnWindowDays)||DEFAULT_STORE_SETTINGS.returnWindowDays),maintenanceMode:Boolean(data.maintenanceMode),commerceMode:data.commerceMode==="live"?"live":"portfolio"});},(error)=>onError?.(error));}
export async function saveStoreSettings(settings:StoreOperationsSettings,actor:{uid:string;displayName:string}){
  if(!settings.storeName.trim()||!settings.supportEmail.includes("@"))throw new Error("Store name aur valid support email required hain.");
  if(settings.commerceMode==="live"&&settings.gatewayIntegration!=="configured")throw new Error("Live commerce mode ke liye verified gateway configuration required hai.");
  const audit={id:crypto.randomUUID(),action:"settings_updated",actorUid:actor.uid,actorName:actor.displayName,createdAt:new Date().toISOString()};
  const batch=writeBatch(db);batch.set(doc(db,"storeSettings","global"),{...settings,auditTrail:[...settings.auditTrail,audit].slice(-200),updatedAt:serverTimestamp(),updatedBy:actor.uid},{merge:true});
  batch.set(doc(db,"publicStoreSettings","public"),{storeName:settings.storeName,supportEmail:settings.supportEmail,currency:settings.currency,locale:settings.locale,shippingThreshold:settings.shippingThreshold,standardShippingFee:settings.standardShippingFee,returnWindowDays:settings.returnWindowDays,maintenanceMode:settings.maintenanceMode,commerceMode:settings.commerceMode,updatedAt:serverTimestamp()},{merge:true});await batch.commit();
}
